// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProject() {
  return window['go']['main']['App']['CreateProject']();
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function LoadAssets(arg1) {
  return window['go']['main']['App']['LoadAssets'](arg1);
}

export function LoadProject(arg1) {
  return window['go']['main']['App']['LoadProject'](arg1);
}

export function LoadProjects() {
  return window['go']['main']['App']['LoadProjects']();
}

export function SaveAsset(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SaveAsset'](arg1, arg2, arg3, arg4, arg5, arg6);
}
