// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateProject():Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function LoadProject(arg1:string):Promise<main.Project>;

export function LoadProjects():Promise<Array<main.Project>>;
