// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProject() {
  return window['go']['main']['App']['CreateProject']();
}

export function DeleteAsset(arg1, arg2) {
  return window['go']['main']['App']['DeleteAsset'](arg1, arg2);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function GeneratePDF(arg1) {
  return window['go']['main']['App']['GeneratePDF'](arg1);
}

export function LoadAssets(arg1) {
  return window['go']['main']['App']['LoadAssets'](arg1);
}

export function LoadB64Asset(arg1) {
  return window['go']['main']['App']['LoadB64Asset'](arg1);
}

export function LoadModels() {
  return window['go']['main']['App']['LoadModels']();
}

export function LoadProject(arg1) {
  return window['go']['main']['App']['LoadProject'](arg1);
}

export function LoadProjects() {
  return window['go']['main']['App']['LoadProjects']();
}

export function PickImageAndReturnPath() {
  return window['go']['main']['App']['PickImageAndReturnPath']();
}

export function UploadAsset(arg1, arg2) {
  return window['go']['main']['App']['UploadAsset'](arg1, arg2);
}

export function UploadModels() {
  return window['go']['main']['App']['UploadModels']();
}
