// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProject() {
  return window['go']['main']['App']['CreateProject']();
}

export function LoadProjects() {
  return window['go']['main']['App']['LoadProjects']();
}
